### ISSUE TITLE
Not a Issue, just need help :P

### ISSUE THREAD

**Issue by Scrulius** [KellerThompson/MythicFusionWiki#1]
Hey! I'm trying to get a mythicmobs item of AuraSkills stats (for example an armour)

Is this possible? I don't want permanent stats, only when equipped.

Creo que hablas Español, pues eso, hay alguna forma de hacer que un item de Mythicmobs de stats de AuraSkills, si no es así, te costaría mucho añadirlo? sería fantastico, es una caracteristica que mucha gente anhela en el discord de MythicMobs, tu plugin explotaría en descargas :P

**Comment by KellerThompson** [comment]
### Hola! si no se trata de un error puedes unirte al [discord](https://discord.gg/j5y6QmTfDt) y abrir un ticket.

Igualmente te comento que de momento no hay una funcionalidad como la que dices, pero se puede tener un efecto similar de la siguiente manera:

## Usando MythicFusion Trinkets
* Creas un trinket, puedes seguir el ejemplo en mi [Wiki](https://github.com/KellerThompson/MythicFusionWiki/wiki/Fusion-Items#-example)
* En la skill del trinket otorgas un [Aura](https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/skills/mechanics/aura) al jugador donde la metaSkill `onStartSkill` utilices mi mecánica custom [AddStat](https://github.com/KellerThompson/MythicFusionWiki/wiki/AuraSkills-Fusion#-addstat) y como metaSkill `onEndSkill` cancelas el efecto con mi mecánica [RemoveStat](https://github.com/KellerThompson/MythicFusionWiki/wiki/AuraSkills-Fusion#-removestat).

### Terminarías teniendo algo como esto:
```
myTrinketName:
  Skills:
    - Aura{auraName=healthBuffAura; duration=200; onStartSkill=startBuff; onEndSkill=endBuff;} @self

startBuff:
  Skills:
      - AddStat{name=healthBuff; stat=HEALTH; value=50;}

endBuff:
  Skills:
      - RemoveStat{name=healthBuff;}
```

## Usando AuraSkills
Como alternativa siempre puedes ocupar los comandos del plugin AuraSkills `/skill item` o `/skill armor` para agregar manualmente modificadores a los objetos.
